import { useState } from 'react';
import { useRouter } from 'next/router'
import type { NextPage } from 'next'
import Head from 'next/head'

import { PrimaryButton } from '../components/Button';
import { Input } from '../components/Input';

import { Flex, Stack } from '@chakra-ui/react';

const Home: NextPage = () => {
  const router = useRouter();
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');

  const handleSubmit = (e:any) => {
    e.preventDefault();

    if (email.length > 0 && password.length > 0) {
      router.push('/dashboard')
    }
  }

  return (
    <>
      <Head>
        <title>Chakra UI | Next | TypeScrypt</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex
        w="100vw"
        h="100vh"
        align="center"
        justify="center">
        
        <Flex
          as="form"
          w="100%"
          maxW="400px"
          justify="center"
          borderRadius="8px"
          flexDir="column"
          onSubmit={handleSubmit}>

          <Stack spacing="4">
            <Input type="email" name="email" label="E-mail" onChange={e => setEmail(e.target.value)} />
            <Input type="password" name="password" label="Senha" onChange={e => setPassword(e.target.value)} />
          </Stack>
          
          <PrimaryButton text="Entrar" mt="6" size="lg" type="submit" />
          
        </Flex>
      
      </Flex>
    </>
  )
}

export default Home
function submitForm() {
  throw new Error('Function not implemented.');
}

